services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend


  backend:
    build:
      context: ./backend
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


  postgres:
    image: postgres:17
    container_name: ecommerce-postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: